### PR TITLE
Use of FakeIt as a dependency with supporting fixes

### LINKED ISSUE #44: Upgrade the `fakeit` lib?
https://github.com/FabioBatSilva/ArduinoFake/tree/master/src/fakeit – currently it is a hardcoded, very old version.

I actually came here to fix a few issues that the lib is throwing at me, when I build my tests with `-Wpedantic`. But I see what's going on now -> and I don't think trying to fix the old hardcoded version would be a good idea ;-)

A better one would be:
1. Upgrade `fakeit` to its latest available version.
2. Not hardcode it anymore -> maybe download it with PIO's `lib_deps`?

### PR DESCRIPTION
**Pull request by RobertByrnes**
@FabioBatSilva ok here goes again. This PR has edited the CMakeList.txt files to pull in FakeIt as a dependency - using latest currently 4.2.0.

In addition to this there are three supporting fixes:

A change from map to unordered_map in ArduinoFake which achieves the same result and avoids an ambiguous reference conflicting with the Arduino map function.

A change to the method setup and verification to use const char* instead of const char[]. This matches the actual method signature in the Arduino Print library for printing C-style strings (which are essentially const char*). Print class.

Use of a single pointer in test setup and assertions in the client class.

This would close #44

### CODE REVIEW

**Comment by nerdyscout** [comment]
I am currently trying to include this into some project but it fails. Seems like `/ArduinoFake/src/ArduinoFake.h` includes `fakeit.hpp` but this is actually deleted by the PR. dont know yet what I do wrong, havn't figured out how the dependency should be pulled.

**Comment by RobertByrnes** [comment]
Arh I missed that! Make brings it in for building with 'make' and running the tests with 'make test'.

I hadn't added the fake it repo to the platformio.ini!

I will be able to look at that tomorrow in the meantime maybe try it ... lib_deps=https://github .... fakeit url ...

**Comment by nerdyscout** [comment]
thank you for the quick reply.
yes it solved the dependencies, but (atleast my) built system is still not able to find the fakeit.hpp. will check out some when later.

**Comment by RobertByrnes** [comment]
No worries. I'll take another look tomorrow. I am curious to see what happens when the workflow runs now....

**Comment by RobertByrnes** [comment]
@nerdyscout Have another go at this - the trick here was that FakeIt produces several fakeit.hpp files in subdirectories so dependency resolution was doomed. That is now sorted.

@FabioBatSilva this should now be there - as in, FakeIt being pulled in as a dependency handled within the make pipeline. This is currently set to 4.2.0 in the external/fakeit/CMakeLists.txt file and can be edited from there. There were 3 fixes for change to ArduinoFake to make it work but none of them are/were breaking

**Review by FabioBatSilva — APPROVED** [review]
Thanks @RobertByrnes :+1: 

Awesome work here,
Will tag this as a new major version

**Comment by RobertByrnes** [comment]
I don't feel it's complete until the FakeiIt version is no longer hard baked into the make file but this is a step 😀

**Pull request merged**
